export const API_ENDPOINTS = {
    LOGIN: `/login`,
    LOGOUT: `/logout`,
    USER_PROFILE: `/profile`,
    USER_PROFILE_EDIT: `/profile/edit`,
    REGISTER_DOCTOR: `/doctor/resgister`,
    REGISTER_STAFF: `/staff/resgister`,
    REGISTER_PATIENT: `/patient/resgister`,
    ALL_PATIENTS: `/patients`,
    ALL_DOCTORS: `/doctors`,
    ALL_STAFFS: `/staffs`,
    ADD_CHECKUP: `/checkup/new`,
    ALL_CHECKUP: `/checkups`,
    ADD_REASON: `/reason/new`,
    ADD_MEDICAL_HISTORY: `/medicalHistory/new`,
    ALL_MEDICAL_HISTORY: `/medicalHistories`,
    ADD_MEDICAL_REPORT: `/medicalReport/new`,
    ALL_MEDICAL_REPORT: `/medicalReports`,
    CHANGE_PASSWORD: `/changePassword`,
    FORGOT_PASSWORD: `/forgotPassword`,
    RESET_PASSWORD: `/resetPassword`,
    RESET_PASSWORD: `/resetPassword`,
    DELETE_USER: `/deleteUser`,
    ACCESS_HISTORIES: `/accessHistories`,
    ADD_TEST: `/test/new`,
    ALL_TESTS: `/tests`,
}